core/urls.py
"""
Core URL Configuration
"""

from django.urls import path

from core.views import (
    HomeView,
    GameView,
    GamesView,
    my_games,
    about_page,
    log_in,
    log_out,
    sign_up,
    terms,
)

app_name = "Core"

urlpatterns = [
    path("", HomeView.as_view(), name="homepage"),
    path("about", about_page, name="about"),
    path("terms", terms, name="terms"),
    path("login", log_in, name="login"),
    path("logout", log_out, name="logout"),
    path("signup", sign_up, name="signup"),
    path("game/<str:name>", GamesView.as_view(), name="new_game"),
    path("games", my_games, name="my_games"),
    path("games/<str:name>", my_games, name="my_specific_games"),
    path("game/<str:name>/<int:pk>", GameView.as_view(), name="game"),
]

games/urls.py
"""
Games URL Configuration
"""

from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.utils.translation import gettext_lazy as _

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("oauth/", include("social_django.urls", namespace="social")),
    path("admin/", admin.site.urls),
]

admin.site.site_header = _("Games administration")

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

templates/ConnectFour.html
{% load core_tags %}

<table class="board {{ game.game }}">
  {% for row in game.rules.rows|loop:True %}
    <tr>
      {% for col in game.rules.cols|loop %}
        <td id="{{ row }}-{{ col }}">{{ game.board|get:row|get:col }}</td>
      {% endfor %}
    </tr>
  {% endfor %}
</table>

templates/TicTacToe.html
{% load core_tags %}

<table class="board {{ game.game }}">
  {% for row in game.rules.rows|loop:True reversed %}
    <tr>
      {% for col in game.rules.cols|loop %}
        <td id="{{ row }}-{{ col }}">{{ game.board|get:row|get:col }}</td>
      {% endfor %}
    </tr>
  {% endfor %}
</table>

templates/about.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "About us" %}{% endblock title %}
{% block description %}{% trans 'Online board games' %}{% endblock description %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1 class="mb-4"><wbr>{% trans "About us" %}</h1>
            <p>{% trans "Online board games" %}</p>
            <p>{% trans "Link to the repository:" %} <a href="https://bitbucket.org/voron-raven/games">https://bitbucket.org/voron-raven/games</a></p>
            <p>{% trans "Site owner:" %} <a href="https://www.linkedin.com/in/mykhailokeda/">Mykhailo Keda</a></p>
        </div>
    </div>
{% endblock content %}

templates/base.html
<!doctype html>
{% load static %}
{% load i18n %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QMOFBUIlPIK7gAAAdxJREFUWMPll8FqFEEQhr/+K6IxqAgBEQ+LoiCKkJMH8RFE8RkEjyJ4M3mBHHwYjSdvQkAQYS+LohcTDWpQoyjioukqDzuDu8asG9nZPqSgT1PM93dVd1cV7HZLozqa7DRwBbgInAVagKrPAbwGOsByEEvu3hmLQpPdNtkHk8UO14bJ5tHomwRAUg2++R/Q7dat6p/DU2DJSCkdDOIRcGbM6X4OnCfxJee8VYCZQdCqHPc2dOZ+AqdIrNYiUh0ad5+V9AbY0/DBz+5+RNLH7Ll3irNnJD2ZALy3X6mdvRcBqyKwAFyd4PU/lFKKiHhYpyBKPELZczKTXQMulxCgpLcqBa/skoC5ggLmksm6Dd77f9mm6ptQyLKAdwUFrAtoFxTQFrBUUMC94g9R3dEsFODPD5Zj2UrVZk3CXmbPJwbKMXAYWJ9ARfwBHCXYyNFXjkl8cvw40G0Q3nX8JKkH39KSKQmZ9oXH9wbgnUS64OFfPfw3s99j2qYJjyaK043s+ZwzCP/rXGCyNeDYGKDvgTvZ8+Iwp6k/4NdHgN+vOuZWXx3ZBFaAp8AycDd7frGjWcBkB4b09d9Mtmiy/ePOzRSAu2OyepT6DLwCngXxmOCBx5jGrO1sRjO7dzr+BVtAwsorwcB8AAAAAElFTkSuQmCC" rel="icon"/>
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
  {% block css %}{% endblock css %}
  <title>{% block title %}{% trans "Games" %}{% endblock title %}</title>
  <meta name="description" content="{% block description %}{% trans 'Games site' %}{% endblock description %}"/>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'core:homepage' %}">Games</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        {% url 'core:homepage' as homepage_url %}
        <li class="nav-item">
          <a class="nav-link {% if request.get_full_path == homepage_url %}active{% endif %}" href="{{ homepage_url }}">Home <span class="sr-only">(current)</span></a>
        </li>
        {% if user.is_authenticated %}
        {% url 'core:my_games' as my_games_url %}
        <li class="nav-item">
          <a class="nav-link {% if request.get_full_path == my_games_url %}active{% endif %}" href="{{ my_games_url }}">{% trans 'My games' %}</a>
        </li>
        {% endif %}
        {% url 'core:about' as about_url %}
        <li class="nav-item">
          <a class="nav-link {% if request.get_full_path == about_url %}active{% endif %}" href="{{ about_url }}">{% trans 'About' %}</a>
        </li>
      </ul>

      <ul class="navbar-nav mr-right">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="#">{{ user.username }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:logout' %}">{% trans "Log out" %}</a>
        </li>
        {% else %}
        {% url 'core:login' as login_url %}
        <li class="nav-item">
          <a class="nav-link {% if request.get_full_path == login_url %}active{% endif %}" href="{{ login_url }}">{% trans "Log in" %}</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  {% block content %}{% endblock content %}

  <script src="{% static 'node_modules/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'node_modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-74402136-8', 'auto');
    ga('send', 'pageview');
  </script>
  {% block script %}{% endblock script %}
</body>
</html>

templates/game.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{{ game.game }}{% endblock title %}

{% block content %}
  <div class="container">
    <div class="jumbotron bg-white">
      <h1 class="mb-4">{{ game.pk }}: <a class="text-dark" href="{% url 'core:new_game' game.game %}">{{ game.rules.title }}</a> ({{ players|join:" vs " }})</h1>
      {% include game.game|add:".html" %}
      <div id="info" class="mt-2 text-muted h4">
        <p class="waiting" style="{% if winner != None %}display: none;{% endif %}">{% trans "Waiting for" %} <a id="who_is_going_to_move" href="#">{{ user_turn }}</a> {% trans "move" %}</p>
        <p class="draft" style="{% if winner != -1 %}display: none;{% endif %}">{% trans "It's a draft. Game is over!" %}</p>
        <p class="winner" style="{% if winner == None or winner == -1 %}display: none;{% endif %}"><a id="winner" href="#">{{ winner }}</a> {% trans "win! Game is over!" %}</p>
      </div>
    </div>
  </div>
{% endblock content %}

{% block script %}
  <script>
    let protocol = location.protocol === 'https:' ? 'wss' : 'ws';
    let socket = new WebSocket(protocol + '://' + window.location.host + '/ws/game/' + {{ game.id }});
    let players = {{ players|safe }};
    let $board = $('table.board');
    let $info = $('#info');
    let i;
    let j;

    $board.find('td:empty').click(function() {
      socket.send(JSON.stringify({
        move: this.id
      }));
    });

    socket.onmessage = function message(event) {
      let raw_data = JSON.parse(event.data);
      for (i = 0; i < raw_data.board.length; i++) {
        for (j = 0; j < raw_data.board[i].length; j++) {
          $board.find('td#' + i + '-' + j).html(raw_data.board[i][j]);
        }
      }

      $info.children('p').hide();
      if (raw_data.winner === null) {
        $info.find('#who_is_going_to_move').text(players[raw_data.turn]);
        $info.children('p.waiting').show();
      }
      else if (raw_data.winner === -1) {
        $info.children('p.draft').show();
      }
      else {
        $info.find('#winner').text(players[raw_data.winner]);
        $info.children('p.winner').show();
      }
    };

    if (socket.readyState === WebSocket.OPEN) {
      socket.onopen();
    }
  </script>
{% endblock script %}

templates/games.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Games" %}{% endblock title %}

{% block content %}
  <div class="container">
    <div class="jumbotron bg-white games-container">
      <h1 class="mb-5">My games:</h1>
        {% for game in games %}
          <div class="game-item col-md-3 mb-5">
            <h2 class="mb-3"><a href="{% url 'core:game' game.game game.pk %}">{{ game.pk }}: {{ game.rules.title }}</a></h2>
            {% include game.game|add:".html" %}
          </div>
        {% endfor %}
    </div>
  </div>
{% endblock content %}

templates/homepage.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Online board games" %}{% endblock title %}

{% block content %}
  <div class="container">
    <div class="games jumbotron bg-white">
    {% for game in games %}
      <div class="card">
        <img class="card-img-top" src="{% static 'img/'|add:game.classname|add:'.svg' %}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">
            <a class="text-dark" href="{% url 'core:new_game' game.classname %}">{% trans game.title %}</a>
          </h5>
          <p class="card-text">{% trans game.description %}</p>
          <form action="{% url 'core:new_game' game.classname %}" method="post">
            {% csrf_token %}
            <label for="{{ game.classname }}-opponent">{% trans "Opponent" %}</label>
            <select id="{{ game.classname }}-opponent" name="opponent" class="form-control">
              {% for opponent in users %}
                <option value="{{ opponent.pk }}">{{ opponent.username }}</option>
              {% endfor %}
            </select>
            <button type="submit" class="btn btn-primary float-right mt-2">{% trans "Play" %}</button>
          </form>
        </div>
      </div>
    {% endfor %}
    </div>
  </div>
{% endblock content %}

templates/login.html
{% extends 'base.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block title %}{% trans "Login" %}{% endblock title %}
{% block description %}{% trans 'Login to chat with users and chatbot' %}{% endblock description %}

{% block content %}
<div class="container">
  <div class="jumbotron">
  <form action="{% url 'core:login' %}" method="post" class="">
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group row">
        <label class="col-sm-3 col-form-label" for="{{ field.auto_id }}">{{ field.label }}</label>
        <div class="col-sm-9">
        {{ field|add_class:"form-control" }}
        {% if field.errors %}
        <div class="alert alert-warning col-sm-9 offset-sm-3" role="alert">
          {{ field.errors }}
        </div>
        {% endif %}
        </div>
      </div>
    {% endfor %}
    {% if form.non_field_errors %}
      <div class="alert alert-warning col-sm-9 offset-sm-3" role="alert">
        {{ form.non_field_errors }}
      </div>
    {% endif %}
    <button type="submit" class="btn btn-primary float-right">{% trans "Log in" %}</button>
  </form>


  <a href="{% url 'social:begin' 'facebook' %}">{% trans "Login with Facebook" %}</a>
  <p>{% trans "Don't have an account?" %} <a href="{% url 'core:signup' %}">{% trans "Sign up!" %}</a></p>
  </div>
</div>
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block title %}{% trans "Sign up" %}{% endblock title %}
{% block description %}{% trans 'Sign up to chat with users or chatbot' %}{% endblock description %}

{% block content %}
<div class="container">
  <div class="jumbotron">
  <form action="{% url 'core:signup' %}" method="post">
    {% csrf_token %}
    {% if form.non_field_errors %}
    <div class="alert alert-warning col-sm-9 offset-sm-3" role="alert">
      {{ form.non_field_errors }}
    </div>
    {% endif %}
    {% for field in form %}
      <div class="form-group row">
        <label class="col-sm-3 col-form-label" for="{{ field.auto_id }}">{{ field.label }}</label>
        <div class="col-sm-9">
        {{ field|add_class:"form-control" }}
        </div>
        {% if field.errors %}
        <div class="alert alert-warning col-sm-9 offset-sm-3" role="alert">
          {{ field.errors }}
        </div>
        {% endif %}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary float-right">{% trans "Sign up" %}</button>
    <p>{% trans "Already have an account?" %} <a href="{% url 'core:login' %}">{% trans "Log in!" %}</a></p>
  </form>
  </div>
</div>
{% endblock content %}